seleniumGrid =true
gridURL = http://localhost:4444/wd/hub

#Application URL
url = https://opensource-demo.orangehrmlive.com/web/index.php/auth/login

#Browser Configuration
browser = chrome

#credentials
username = Admin
password = admin123

#Implicit wait (in seconds)
implicitwait = 30

#explicit wait (in seconds)
explicitwait = 60